name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install mdbook
        uses: taiki-e/install-action@mdbook
      - name: Install mdbook-linkcheck
        uses: taiki-e/install-action@mdbook-linkcheck
      - run: mdbook build

  # Check documentation links aren't broken
  link-checker:
    uses: argumentcomputer/ci-workflows/.github/workflows/links-check.yml@main
