name: Build and deploy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@mdbook
      - run: mdbook build
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book
          retention-days: 1

  # Check links aren't broken
  link-checker:
    uses: argumentcomputer/ci-workflows/.github/workflows/links-check.yml@main
    with: 
      fail-fast: true

  deploy:
    if: github.ref_name == 'main' && github.event_name == 'push'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
